version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "node-crud-todo-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l2pmtde12dfy"
s3_prefix = "node-crud-todo-api"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Table=\"Todos\" Region=\"ap-south-1\""
image_repositories = []
